# Generated by Django 4.1 on 2022-09-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercaderia',
            name='fecha_vencimiento',
        ),
    ]
